// <auto-generated />
using LocaFacil;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocaFacil.Migrations
{
    [DbContext(typeof(LocaFacilContext))]
    partial class LocaFacilContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasCharSet("latin1")
                .UseCollation("latin1_swedish_ci")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("LocaFacil.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Numero")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<int>("UfId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UfId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("LocaFacil.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("LocatarioId")
                        .HasColumnType("int");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoImovelId")
                        .HasColumnType("int");

                    b.Property<decimal>("VagaGaragem")
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal>("ValorAluguel")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("ValorCondominio")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("ValorIPTU")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("LocatarioId");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("TipoImovelId");

                    b.ToTable("Imovel");
                });

            modelBuilder.Entity("LocaFacil.Models.Locatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("TelefoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("Locatario");
                });

            modelBuilder.Entity("LocaFacil.Models.Proprietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("TelefoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("Proprietario");
                });

            modelBuilder.Entity("LocaFacil.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ddd")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.HasKey("Id");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("LocaFacil.Models.TipoImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("TipoImovel");
                });

            modelBuilder.Entity("LocaFacil.Models.Uf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Uf");
                });

            modelBuilder.Entity("LocaFacil.Models.Endereco", b =>
                {
                    b.HasOne("LocaFacil.Models.Uf", "Uf")
                        .WithMany("Enderecos")
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("LocaFacil.Models.Imovel", b =>
                {
                    b.HasOne("LocaFacil.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocaFacil.Models.Locatario", "Locatario")
                        .WithMany("Imoveis")
                        .HasForeignKey("LocatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocaFacil.Models.Proprietario", "Proprietario")
                        .WithMany("Imoveis")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocaFacil.Models.TipoImovel", "TipoImovel")
                        .WithMany("Imoveis")
                        .HasForeignKey("TipoImovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Locatario");

                    b.Navigation("Proprietario");

                    b.Navigation("TipoImovel");
                });

            modelBuilder.Entity("LocaFacil.Models.Locatario", b =>
                {
                    b.HasOne("LocaFacil.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocaFacil.Models.Telefone", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("LocaFacil.Models.Proprietario", b =>
                {
                    b.HasOne("LocaFacil.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocaFacil.Models.Telefone", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("LocaFacil.Models.Locatario", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("LocaFacil.Models.Proprietario", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("LocaFacil.Models.TipoImovel", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("LocaFacil.Models.Uf", b =>
                {
                    b.Navigation("Enderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
