-- MySQL Script generated by MySQL Workbench
-- Thu Jan  6 05:19:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brunsker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brunsker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brunsker` DEFAULT CHARACTER SET latin1 ;
USE `brunsker` ;

-- -----------------------------------------------------
-- Table `brunsker`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brunsker`.`uf` (
  `id_uf` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(2) NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_uf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brunsker`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brunsker`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `bairro` VARCHAR(40) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `numero` VARCHAR(12) NOT NULL,
  `complemento` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(60) NOT NULL,
  `id_uf` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_uf1_idx` (`id_uf` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_uf1`
    FOREIGN KEY (`id_uf`)
    REFERENCES `brunsker`.`uf` (`id_uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `brunsker`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brunsker`.`telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `ddd` VARCHAR(3) NULL DEFAULT '31',
  `numero` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_telefone`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `brunsker`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brunsker`.`proprietario` (
  `id_proprietario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `id_endereco` INT NOT NULL,
  `id_telefone` INT NOT NULL,
  PRIMARY KEY (`id_proprietario`),
  INDEX `fk_proprietario_endereco1_idx` (`id_endereco` ASC) VISIBLE,
  INDEX `fk_proprietario_telefone1_idx` (`id_telefone` ASC) VISIBLE,
  CONSTRAINT `fk_proprietario_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `brunsker`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proprietario_telefone1`
    FOREIGN KEY (`id_telefone`)
    REFERENCES `brunsker`.`telefone` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `brunsker`.`locatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brunsker`.`locatario` (
  `id_locatario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `id_endereco` INT NOT NULL,
  `id_telefone` INT NOT NULL,
  PRIMARY KEY (`id_locatario`),
  INDEX `fk_locatario_endereco1_idx` (`id_endereco` ASC) VISIBLE,
  INDEX `fk_locatario_telefone1_idx` (`id_telefone` ASC) VISIBLE,
  CONSTRAINT `fk_locatario_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `brunsker`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locatario_telefone1`
    FOREIGN KEY (`id_telefone`)
    REFERENCES `brunsker`.`telefone` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `brunsker`.`tipo_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brunsker`.`tipo_imovel` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `brunsker`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brunsker`.`imovel` (
  `id_imovel` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_imovel` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `valor_aluguel` DECIMAL NOT NULL,
  `valor_condominio` DECIMAL NULL,
  `valor_iptu` DECIMAL NULL,
  `id_proprietario` INT NOT NULL,
  `id_locatario` INT NULL,
  `descricao` BLOB NULL,
  PRIMARY KEY (`id_imovel`),
  INDEX `fk_imovel_endereco_idx` (`id_endereco` ASC) VISIBLE,
  INDEX `fk_imovel_proprietario1_idx` (`id_proprietario` ASC) VISIBLE,
  INDEX `fk_imovel_locatario1_idx` (`id_locatario` ASC) VISIBLE,
  INDEX `fk_imovel_tipo_imovel1_idx` (`id_tipo_imovel` ASC) VISIBLE,
  CONSTRAINT `fk_imovel_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `brunsker`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_proprietario1`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `brunsker`.`proprietario` (`id_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_locatario1`
    FOREIGN KEY (`id_locatario`)
    REFERENCES `brunsker`.`locatario` (`id_locatario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_tipo_imovel1`
    FOREIGN KEY (`id_tipo_imovel`)
    REFERENCES `brunsker`.`tipo_imovel` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `brunsker`.`uf`
-- -----------------------------------------------------
START TRANSACTION;
USE `brunsker`;
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (1, 'AC', 'Acre');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (2, 'AL', 'Alagoas');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (3, 'AP', 'Amapá');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (4, 'AM', 'Amazonas');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (5, 'BA', 'Bahia');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (6, 'CE', 'Ceara');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (7, 'DF', 'Distrito Federal');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (8, 'ES', 'Espírito Santo');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (9, 'GO', 'Goiás');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (10, 'MA', 'Maranhão');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (11, 'MT', 'Mato Grosso');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (12, 'MS', 'Mato Grosso do Sul');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (13, 'MG', 'Minas Gerais');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (14, 'PA', 'Pará');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (15, 'PB', 'Paraíba');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (16, 'PR', 'Paraná');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (17, 'PE', 'Pernambuco');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (18, 'PI', 'Piauí');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (19, 'RJ', 'Rio de Janeiro');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (20, 'RN', 'Rio Grande do Norte');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (21, 'RS', 'Rio Grande do Sul');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (22, 'RO', 'Rondônia');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (23, 'RR', 'Roraima');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (24, 'SC', 'Santa Catarina');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (25, 'SP', 'São Paulo');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (26, 'SE', 'Sergipe');
INSERT INTO `brunsker`.`uf` (`id_uf`, `sigla`, `nome`) VALUES (27, 'TO', 'Tocantins');

COMMIT;

